WITH CTE 
AS
(
SELECT
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    {{day_type('STARTED_AR')}} DAY_TYPE,
    {{get_season('STARTED_AT')}} AS STATION_OF_YEAR,
    {{function1('STARTED_AT')}} AS PAST_FUTURE
from {{ source('demo', 'bike_aws') }}

)

SELECT * FROM CTE