#https://docs.getdbt.com/reference/resource-properties/database


sources:
  - name: demo
    database: demo
    schema: demo_schema
    tables:
      - name: bike_aws
      - name: weather
  - name: btc
    database: btc
    schema: btc_schema
    tables:
      - name: btc
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 3
            period: hour
        loaded_at_field: BLOCK_TIMESTAMP
        